### ISSUE TITLE
Acid rain effects without rain

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/PyroWeather#13]
Spigot 1.12.2 latest
PyroWeather 1.3.0

My configuration is AllRainAcid:true in a single world.

It doesn't rain in Savanna biome, but I still take acid rain effects.

**Comment by MostWantedMinx** [comment]
Will add that to the list of safe biomes next update.

**Comment by SlimeDog** [comment]
Please ensure that the safe-from-rain list includes all dry/warm biomes:
**Desert** ----- id=2
**Desert M** ----- id=130  
**Savanna** ----- id=35
**Savanna M** ----- id=163  
**Mesa** ----- id=37  
**Mesa (Bryce)** ----- id=165  
**Mesa Plateau F** ----- id=38
**Mesa Plateau F M** ----- id=166  
**Plateau** ----- id=36, 39  
**Plateau M** ----- id=164, 167  
**Hell (The Nether)** ----- id=8

**Comment by SlimeDog** [comment]
Biome ENUMs are [here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html).

**Comment by SlimeDog** [comment]
Any progress, or will this be combined with MC/Spigot 1.13 release?

**Comment by SlimeDog** [comment]
I see that the 2.0.0 configuration includes
```
  DisabledBiomes:
    - 'Nether'
```
That should do the trick, but please add all the "safe" biomes by default. :)

**Comment by MostWantedMinx** [comment]
Will add all dry / warm biomes in v2.0.2 as default in the configuration file.
