### ISSUE TITLE
Feature request: Multiple potion effects

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/PyroWeather#6]
Spigot 1.12.2 latest
PW 1.2.1

It looks like only one configured potion is being introduced at each damage invocation. I want them all, every time.

**Comment by MostWantedMinx** [comment]
Suggestion has been added for the next release.

**Comment by SlimeDog** [comment]
They need to be reset at every damage point, so that they don't expire until the player is out of the rain. At present, I have them set to 25 seconds, but they count down to 0 and are then re-invoked at the next damage point. So the player is without potion effects for a few seconds, then on again.
