### ISSUE TITLE
Feature request: Take damage without "hit"

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/PyroWeather#7]
Spigot 1.12.2 latest
PW 1.2.1

The "hits" for damage are incongruous for acid rain. Can damage be inflicted without the knockabout?

**Comment by MostWantedMinx** [comment]
Yes this can be done. However it would be so the players health depletes without any warning like a hit indicator. Is this what you want?

**Comment by SlimeDog** [comment]
Depleting hearts is enough visual cue for me. But make it an option, and everyone will be satisfied. :)
